try{
    let result = a = 2+b
} catch(error)
{
    console.log(error)
}